name: Deploy FirstMVC

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x'
  PROJECT_PATH: './FirstMVC/FirstMVC.fsproj'
  PUBLISH_PATH: './publish'
  WEBSITE_PATH: 'C:\inetpub\wwwroot\FirstMVC'
  IIS_SITE_NAME: 'FirstMVC'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_PATH }}

      - name: Stop IIS Site
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-Website -Name "${{ env.IIS_SITE_NAME }}"

      - name: Copy Files
        shell: powershell
        run: |
          Copy-Item `
            "${{ github.workspace }}\publish\*" `
            "${{ env.WEBSITE_PATH }}" `
            -Recurse -Force

      - name: Start IIS Site
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-Website -Name "${{ env.IIS_SITE_NAME }}"